import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import Database from 'better-sqlite3';
const dir=path.resolve('evidence/handover-audit-20260908');
const database=path.join(dir,`latest-${Date.now()}.db`);
process.env.DATABASE_URL=`file:${database.replaceAll('\\','/')}`;
process.env.LLM_MODE='mock'; process.env.SEMANTIC_MEMORY_ENABLED='false'; process.env.EVIDENCE_TRUST_RECEIPT_ENABLED='true';
const files=['lib/services/changeImpactService.ts','lib/services/copilotService.ts','lib/services/attachmentService.ts','lib/repositories/cards.ts'];
const hashes=()=>Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')]));
const before=hashes(); const sql=new Database(database);
for(const name of fs.readdirSync('prisma/migrations').sort()){const p=path.join('prisma/migrations',name,'migration.sql');if(fs.existsSync(p))sql.exec(fs.readFileSync(p,'utf8'));}sql.close();
const {db}=await import('../../lib/db');
const {analyzeChangeImpact,confirmChangeImpact}=await import('../../lib/services/changeImpactService');
const {executeCopilotTool}=await import('../../lib/services/copilotService');
const {completeProjectAction}=await import('../../lib/services/actionService');
const {confirmDeliverableEvidence}=await import('../../lib/services/milestoneService');
const {correctAttachmentText}=await import('../../lib/services/attachmentService');
async function attempt(fn:()=>Promise<unknown>){try{return {accepted:true,result:await fn()};}catch(e){return {accepted:false,error:String(e)};}}
const a=await db.project.create({data:{title:'最新审查A',description:'隔离',goal:'验证',scenario:'RESEARCH'}});
const b=await db.project.create({data:{title:'最新审查B',description:'隔离',goal:'验证',scenario:'RESEARCH'}});
async function card(projectId:string,title:string){const c=await db.capture.create({data:{projectId,rawText:title}});return db.knowledgeCard.create({data:{projectId,captureId:c.id,title,summary:title,type:'meeting_note',keywords:[],relatedTasks:[],nextActions:[],importance:3}});}
const old=await card(a.id,'模型方案A'); const alternate=await card(a.id,'完全无关的会议安排');const foreign=await card(b.id,'项目B旧决策');
const act=await db.actionItem.create({data:{projectId:a.id,title:'报销差旅',status:'TODO'}});
const p=await analyzeChangeImpact(a.id,'模型方案A改为方案B');
const base={proposalId:p.proposalId,newFactText:p.newFactText,supersededCardId:p.supersededCardId,cancelledActionIds:[],newActions:[]};
const bogus=await attempt(()=>confirmChangeImpact(a.id,{...base,proposalId:'fake'}));
const cross=await attempt(()=>confirmChangeImpact(a.id,{...base,supersededCardId:foreign.id}));
const chosen=p.supersededCardId===old.id?alternate:old;
const tamper=await attempt(()=>confirmChangeImpact(a.id,{...base,newFactText:'未经预览的替换事实内容',supersededCardId:chosen.id,cancelledActionIds:[act.id]}));
const again=await attempt(()=>confirmChangeImpact(a.id,base));
const run=await db.agentRun.create({data:{projectId:a.id,runType:'CHAT',status:'SUCCESS',provider:'audit',trace:{supportState:'SUPPORTED'},resultJson:{proposedActions:[{kind:'create_action',title:'并发建议',priority:2}]}}});
const input={tool:'create_action' as const,confirmed:true,sourceRunId:run.id,payload:{title:'并发建议',priority:5}};
const concurrency=await Promise.all([attempt(()=>executeCopilotTool(a.id,input)),attempt(()=>executeCopilotTool(a.id,input))]);
const completeAct=await db.actionItem.create({data:{projectId:a.id,title:'新卡后的行动',status:'TODO'}});
const completion=await attempt(()=>completeProjectAction(a.id,completeAct.id,'完成新的真实实验回执'));
const attachment=await db.attachment.create({data:{projectId:a.id,type:'IMAGE',storageKey:'audit/no-file',fileName:'audit.png',mimeType:'image/png',size:1,sha256:'audit',extractionStatus:'FAILED'}});
const milestone=await db.milestone.create({data:{projectId:a.id,title:'实验交付'}});
const deliverable=await db.deliverable.create({data:{milestoneId:milestone.id,title:'图片证据',expectedEvidence:JSON.stringify(['image_attachment'])}});
await confirmDeliverableEvidence({projectId:a.id,deliverableId:deliverable.id,evidenceType:'image_attachment',attachmentId:attachment.id,confirmed:true});
const correction1=await correctAttachmentText(a.id,attachment.id,'实验准确率为百分之八十，尚未达标');
const correction2=await correctAttachmentText(a.id,attachment.id,'人工核对后准确率为百分之九十，已达标');
const result={database,before,after:hashes(),previewSelectedCard:p.supersededCardTitle,unrelatedCancellationSuggested:p.impactedActions.some(x=>x.targetId===act.id),bogus,cross,tamper,again,copilotAccepted:concurrency.map(x=>x.accepted),copilotCount:await db.actionItem.count({where:{projectId:a.id,title:'并发建议'}}),completionAccepted:completion.accepted,completionError:completion.error,failedAttachmentCanCompleteDeliverable:(await db.deliverable.findUnique({where:{id:deliverable.id}}))?.status,correctionCardCount:await db.knowledgeCard.count({where:{attachmentId:attachment.id}}),correctionSupersession:await db.cardRelation.count({where:{currentCardId:correction2.card.id,relatedCardId:correction1.card.id,relationType:'SUPERSEDES'}})};
await db.$disconnect();fs.writeFileSync(path.join(dir,'latest-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
